#!/bin/bash

NGINX_NO_BUFFER=${NGINX_NO_BUFFER:-false}

cp /etc/nginx/conf.d/proxyserver.template /etc/nginx/conf.d/default.conf
sed -i -e "s|\${NGINX_SERVER_NAME}|$NGINX_SERVER_NAME|g" /etc/nginx/conf.d/default.conf
sed -i -e "s|\${NGINX_REMOTE_URL}|$NGINX_REMOTE_URL|g" /etc/nginx/conf.d/default.conf

if [ $NGINX_NO_BUFFER = true ]; then
    sed -i -e "/\s*[^#]location \/ {/a \ \ \ \ \ \ \ \ proxy_buffering off;" /etc/nginx/conf.d/default.conf
fi

exec nginx -g 'daemon off;'