#!/bin/bash
cp /etc/nginx/conf.d/proxyserver.template /etc/nginx/conf.d/default.conf
sed -i -e "s|\${NGINX_SERVER_NAME}|$NGINX_SERVER_NAME|g" /etc/nginx/conf.d/default.conf
sed -i -e "s|\${NGINX_REMOTE_URL}|$NGINX_REMOTE_URL|g" /etc/nginx/conf.d/default.conf

exec nginx -g 'daemon off;'